# Makefile для HTML-документа об алгоритме Евклида
# Автор: Хамза Хуссен

.PHONY: all clean view help

# Имя файла
HTML_FILE = euclid_algorithm.html

# Цель по умолчанию
all: $(HTML_FILE)

# Создание HTML файла
$(HTML_FILE):
	@echo "Создание HTML файла..."
	@echo '<!DOCTYPE html>' > $(HTML_FILE)
	@echo '<html lang="ru">' >> $(HTML_FILE)
	@echo '<head>' >> $(HTML_FILE)
	@echo '    <meta charset="UTF-8">' >> $(HTML_FILE)
	@echo '    <title>Лабораторная работа №4 - Алгоритм Евклида</title>' >> $(HTML_FILE)
	@echo '</head>' >> $(HTML_FILE)
	@echo '<body>' >> $(HTML_FILE)
	@echo '    <h1>Лабораторная работа №4</h1>' >> $(HTML_FILE)
	@echo '    <h2>Алгоритм Евклида</h2>' >> $(HTML_FILE)
	@echo '    <p><b>Студент:</b> Хамза Хуссен</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h2>1. Введение: цели и задачи исследования</h2>' >> $(HTML_FILE)
	@echo '    <p>Основная цель работы — ознакомиться с классическим алгоритмом Евклида для вычисления наибольшего общего делителя (НОД), а также изучить его модификации: бинарный и расширенный варианты.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h2>2. Теоретическая часть</h2>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h3>2.1 Понятие наибольшего общего делителя (НОД)</h3>' >> $(HTML_FILE)
	@echo '    <p>Наибольшим общим делителем двух целых чисел называется наибольшее натуральное число, которое делит оба числа без остатка. НОД играет важную роль в теории чисел, криптографии и алгоритмизации.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h3>2.2 Классический алгоритм Евклида</h3>' >> $(HTML_FILE)
	@echo '    <p>Данный алгоритм основан на последовательном делении с остатком и основывается на следующем равенстве:</p>' >> $(HTML_FILE)
	@echo '    <p><b>НОД(a,b)=НОД(b,a mod b)</b></p>' >> $(HTML_FILE)
	@echo '    <p>где a≥b>0.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h4>Этапы алгоритма:</h4>' >> $(HTML_FILE)
	@echo '    <p>1. Пусть r_0=a, r_1=b, i=1.</p>' >> $(HTML_FILE)
	@echo '    <p>2. Найти остаток r_(i+1) от деления r_(i-1) на r_i.</p>' >> $(HTML_FILE)
	@echo '    <p>3. Если r_(i+1)=0, то НОД=r_i.</p>' >> $(HTML_FILE)
	@echo '    <p>4. Иначе увеличить i на 1 и вернуться к шагу 2.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h4>Пример: Найдём НОД(30, 18):</h4>' >> $(HTML_FILE)
	@echo '    <p>30 ÷ 18 = 1 (остаток 12)</p>' >> $(HTML_FILE)
	@echo '    <p>18 ÷ 12 = 1 (остаток 6)</p>' >> $(HTML_FILE)
	@echo '    <p>12 ÷ 6 = 2 (остаток 0)</p>' >> $(HTML_FILE)
	@echo '    <p>НОД равен 6.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h3>2.3 Бинарный алгоритм Евклида</h3>' >> $(HTML_FILE)
	@echo '    <p>Эта оптимизированная версия использует двоичное представление чисел и заменяет деление операциями сдвига, что повышает производительность.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h4>Основные принципы:</h4>' >> $(HTML_FILE)
	@echo '    <p>• Если оба числа чётные, то НОД содержит множитель 2.</p>' >> $(HTML_FILE)
	@echo '    <p>• Если одно число чётное, его можно поделить на 2.</p>' >> $(HTML_FILE)
	@echo '    <p>• Если оба нечётные, выполняется вычитание.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h4>Алгоритм:</h4>' >> $(HTML_FILE)
	@echo '    <p>1. Инициализировать множитель g=1.</p>' >> $(HTML_FILE)
	@echo '    <p>2. Пока a и b чётные, делить их на 2 и удваивать g.</p>' >> $(HTML_FILE)
	@echo '    <p>3. Присвоить u=a, v=b.</p>' >> $(HTML_FILE)
	@echo '    <p>4. Выполнять цикл, пока u≠0:</p>' >> $(HTML_FILE)
	@echo '    <p>   • Делить u и v на 2, пока они чётные.</p>' >> $(HTML_FILE)
	@echo '    <p>   • Если u≥v, то u=u-v, иначе v=v-u.</p>' >> $(HTML_FILE)
	@echo '    <p>5. Результат: d=g⋅v.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h3>2.4 Расширенный алгоритм Евклида</h3>' >> $(HTML_FILE)
	@echo '    <p>Позволяет не только вычислить НОД, но и найти коэффициенты x и y для линейного представления:</p>' >> $(HTML_FILE)
	@echo '    <p><b>a⋅x+b⋅y=НОД(a,b)</b></p>' >> $(HTML_FILE)
	@echo '    <p>Это особенно полезно для решения диофантовых уравнений и в алгоритмах модульной арифметики.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h4>Этапы алгоритма:</h4>' >> $(HTML_FILE)
	@echo '    <p>1. Инициализировать последовательности:</p>' >> $(HTML_FILE)
	@echo '    <p>   r_0=a, r_1=b, x_0=1, x_1=0, y_0=0, y_1=1, i=1.</p>' >> $(HTML_FILE)
	@echo '    <p>2. Найти частное q_i и остаток r_(i+1) от деления r_(i-1) на r_i.</p>' >> $(HTML_FILE)
	@echo '    <p>3. Если остаток равен 0, результат: d=r_i, x=x_i, y=y_i.</p>' >> $(HTML_FILE)
	@echo '    <p>4. Иначе вычислить новые коэффициенты:</p>' >> $(HTML_FILE)
	@echo '    <p>   x_(i+1)=x_(i-1)-q_i⋅x_i,</p>' >> $(HTML_FILE)
	@echo '    <p>   y_(i+1)=y_(i-1)-q_i⋅y_i,</p>' >> $(HTML_FILE)
	@echo '    <p>   увеличить i и вернуться к шагу 2.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h2>3. Выполнение работы</h2>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h3>3.1 Реализация алгоритмов на языке Python</h3>' >> $(HTML_FILE)
	@echo '    <pre>' >> $(HTML_FILE)
	@echo 'def euklid_simply(a, b):' >> $(HTML_FILE)
	@echo '    while a != 0 and b != 0:' >> $(HTML_FILE)
	@echo '        if a >= b:' >> $(HTML_FILE)
	@echo '            a = a % b' >> $(HTML_FILE)
	@echo '        else:' >> $(HTML_FILE)
	@echo '            b = b % a' >> $(HTML_FILE)
	@echo '    return a or b' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo 'def euklid_extended(a, b):' >> $(HTML_FILE)
	@echo '    if a == 0:' >> $(HTML_FILE)
	@echo '        return (b, 0, 1)' >> $(HTML_FILE)
	@echo '    else:' >> $(HTML_FILE)
	@echo '        div, x, y = euklid_extended(b % a, a)' >> $(HTML_FILE)
	@echo '    return (div, y - (b // a) * x, x)' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo 'def euklid_binary(a, b):' >> $(HTML_FILE)
	@echo '    g = 1' >> $(HTML_FILE)
	@echo '    while a % 2 == 0 and b % 2 == 0:' >> $(HTML_FILE)
	@echo '        a = a // 2' >> $(HTML_FILE)
	@echo '        b = b // 2' >> $(HTML_FILE)
	@echo '        g = g * 2' >> $(HTML_FILE)
	@echo '    u, v = a, b' >> $(HTML_FILE)
	@echo '    while u != 0:' >> $(HTML_FILE)
	@echo '        if u % 2 == 0:' >> $(HTML_FILE)
	@echo '            u = u // 2' >> $(HTML_FILE)
	@echo '        if v % 2 == 0:' >> $(HTML_FILE)
	@echo '            v = v // 2' >> $(HTML_FILE)
	@echo '        if u >= v:' >> $(HTML_FILE)
	@echo '            u = u - v' >> $(HTML_FILE)
	@echo '        else:' >> $(HTML_FILE)
	@echo '            v = v - u' >> $(HTML_FILE)
	@echo '    d = g * v' >> $(HTML_FILE)
	@echo '    return d' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo 'def euklid_bin_extended(a, b):' >> $(HTML_FILE)
	@echo '    g = 1' >> $(HTML_FILE)
	@echo '    while a % 2 == 0 and b % 2 == 0:' >> $(HTML_FILE)
	@echo '        a = a // 2' >> $(HTML_FILE)
	@echo '        b = b // 2' >> $(HTML_FILE)
	@echo '        g = g * 2' >> $(HTML_FILE)
	@echo '    u = a' >> $(HTML_FILE)
	@echo '    v = b' >> $(HTML_FILE)
	@echo '    A = 1' >> $(HTML_FILE)
	@echo '    B = 0' >> $(HTML_FILE)
	@echo '    C = 0' >> $(HTML_FILE)
	@echo '    D = 1' >> $(HTML_FILE)
	@echo '    while u != 0:' >> $(HTML_FILE)
	@echo '        if u % 2 == 0:' >> $(HTML_FILE)
	@echo '            u = u // 2' >> $(HTML_FILE)
	@echo '            if A % 2 == 0 and B % 2 == 0:' >> $(HTML_FILE)
	@echo '                A = A // 2' >> $(HTML_FILE)
	@echo '                B = B // 2' >> $(HTML_FILE)
	@echo '            else:' >> $(HTML_FILE)
	@echo '                A = (A + b) // 2' >> $(HTML_FILE)
	@echo '                B = (B - a) // 2' >> $(HTML_FILE)
	@echo '        if v % 2 == 0:' >> $(HTML_FILE)
	@echo '            v = v // 2' >> $(HTML_FILE)
	@echo '            if C % 2 == 0 and D % 2 == 0:' >> $(HTML_FILE)
	@echo '                C = C // 2' >> $(HTML_FILE)
	@echo '                D = D // 2' >> $(HTML_FILE)
	@echo '            else:' >> $(HTML_FILE)
	@echo '                C = (C + b) // 2' >> $(HTML_FILE)
	@echo '                D = (D - a) // 2' >> $(HTML_FILE)
	@echo '        if u >= v:' >> $(HTML_FILE)
	@echo '            u = u - v' >> $(HTML_FILE)
	@echo '            A = A - C' >> $(HTML_FILE)
	@echo '            B = B - D' >> $(HTML_FILE)
	@echo '        else:' >> $(HTML_FILE)
	@echo '            v = v - u' >> $(HTML_FILE)
	@echo '            C = C - A' >> $(HTML_FILE)
	@echo '            D = D - B' >> $(HTML_FILE)
	@echo '    d = g * v' >> $(HTML_FILE)
	@echo '    x = C' >> $(HTML_FILE)
	@echo '    y = D' >> $(HTML_FILE)
	@echo '    return (d, x, y)' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo 'a = int(input("Введите первое число (a): "))' >> $(HTML_FILE)
	@echo 'b = int(input("Введите второе число (b): "))' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo 'result1 = euklid_simply(a, b)' >> $(HTML_FILE)
	@echo 'print(f"1. Простой алгоритм Евклида:")' >> $(HTML_FILE)
	@echo 'print(f"   НОД({a}, {b}) = {result1}")' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo 'result2 = euklid_extended(a, b)' >> $(HTML_FILE)
	@echo 'print(f"\n2. Расширенный алгоритм Евклида:")' >> $(HTML_FILE)
	@echo 'print(f"   НОД({a}, {b}) = {result2[0]}")' >> $(HTML_FILE)
	@echo 'print(f"   Коэффициенты: {a}*{result2[1]} + {b}*{result2[2]} = {result2[0]}")' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo 'result3 = euklid_binary(a, b)' >> $(HTML_FILE)
	@echo 'print(f"\n3. Бинарный алгоритм Евклида:")' >> $(HTML_FILE)
	@echo 'print(f"   НОД({a}, {b}) = {result3}")' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo 'result4 = euklid_bin_extended(a, b)' >> $(HTML_FILE)
	@echo 'print(f"\n4. Расширенный бинарный алгоритм:")' >> $(HTML_FILE)
	@echo 'print(f"   НОД({a}, {b}) = {result4[0]}")' >> $(HTML_FILE)
	@echo 'print(f"   Коэффициенты: {a}*{result4[1]} + {b}*{result4[2]} = {result4[0]}")' >> $(HTML_FILE)
	@echo '    </pre>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h2>5. Заключение и выводы</h2>' >> $(HTML_FILE)
	@echo '    <p>В ходе выполнения лабораторной работы:</p>' >> $(HTML_FILE)
	@echo '    <p>• Изучен классический алгоритм Евклида для нахождения НОД.</p>' >> $(HTML_FILE)
	@echo '    <p>• Рассмотрены его оптимизированные версии: бинарный и расширенный алгоритмы.</p>' >> $(HTML_FILE)
	@echo '    <p>• Приведены примеры ручного вычисления НОД каждым из методов.</p>' >> $(HTML_FILE)
	@echo '    <p>• Установлено, что бинарный алгоритм более эффективен для программной реализации благодаря использованию операций сдвига.</p>' >> $(HTML_FILE)
	@echo '    <p>• Расширенный алгоритм Евклида имеет важное практическое применение в криптографических системах и теории чисел.</p>' >> $(HTML_FILE)
	@echo '' >> $(HTML_FILE)
	@echo '    <h2>6. Список использованных источников</h2>' >> $(HTML_FILE)
	@echo '    <p>• Введение в алгоритмы нахождения НОД.</p>' >> $(HTML_FILE)
	@echo '    <p>• Модификации алгоритма Евклида: сравнительный анализ.</p>' >> $(HTML_FILE)
	@echo '    <p>• Материалы лекций по теории чисел и алгоритмам.</p>' >> $(HTML_FILE)
	@echo '</body>' >> $(HTML_FILE)
	@echo '</html>' >> $(HTML_FILE)
	@echo "HTML файл создан: $(HTML_FILE)"

# Открыть HTML файл в браузере
view: $(HTML_FILE)
	@echo "Открытие HTML файла в браузере..."
	@if command -v xdg-open > /dev/null; then \
		xdg-open $(HTML_FILE); \
	elif command -v open > /dev/null; then \
		open $(HTML_FILE); \
	else \
		echo "Не удалось открыть браузер. Откройте файл $(HTML_FILE) вручную."; \
	fi

# Очистка
clean:
	@echo "Удаление HTML файла..."
	@rm -f $(HTML_FILE)

# Справка
help:
	@echo "Доступные команды:"
	@echo "  make all     - Создать HTML файл (цель по умолчанию)"
	@echo "  make         - То же, что make all"
	@echo "  make view    - Создать и открыть HTML файл в браузере"
	@echo "  make clean   - Удалить созданные файлы"
	@echo "  make help    - Показать эту справку"